CREATE DATABASE shopping_db;

USE shopping_db;

CREATE TABLE customer_shopping_behavior (
    customer_id INT PRIMARY KEY,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(50),
    purchase_amount DECIMAL(10,2),
    location VARCHAR(100),
    size VARCHAR(50),
    color VARCHAR(50),
    season VARCHAR(50),
    review_rating DECIMAL(3,2),
    subscription_status VARCHAR(10),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    previous_purchases DECIMAL(10,2),
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50)
);

select * from customer_shopping_behavior;

-- Business Insight Questions

-- 1. Which category generates highest revenue? 
--    Helps prioritise high performing cat, optimises inventory planning, 
--      & improves marketing ROI
select category, round(sum(purchase_amount),2) as highest_revenue from
customer_shopping_behavior group by category order by highest_revenue desc;

-- 2. Are discounts actually increasing purchasing values?
--    Discounts may reduce profit without increasing sales
--     (Identify effectiveness of discounts costs, reduce unnecessary, improve profit margins)
select discount_applied, round(sum(purchase_amount), 2) as total_revenue
from customer_shopping_behavior group by discount_applied;

-- 3. What is the total revenue generated by male and female customer?
-- Understanding revenue contribution by gender segments
-- helps design targeted marketing campaigns, personalisation enhancement.
select gender, round(sum(purchase_amount),2) as highest_revenue from
customer_shopping_behavior group by gender order by highest_revenue desc;

-- 4. Which customer used a discount but still spent more then avg purchase amount?
select customer_id, purchase_amount, discount_applied from
customer_shopping_behavior where discount_applied = "Yes"and purchase_amount > 
(select avg(purchase_amount) from customer_shopping_behavior) 
order by purchase_amount desc limit 10;

-- 5. Which are the top/bottom 5 products with highest avg rating
select item_purchased, avg(review_rating) as avg_rating from 
customer_shopping_behavior group by item_purchased order by avg_rating desc limit 5;

select item_purchased, avg(review_rating) as avg_rating from 
customer_shopping_behavior group by item_purchased order by avg_rating asc limit 5;

-- 6. Avg purchase: Standard vs Express Shipping
select shipping_type, count(distinct customer_id) as order_placed,
round(avg(purchase_amount),2) as avg_purchase , round(sum(purchase_amount),2) 
as revenue from customer_shopping_behavior 
where shipping_type in ('Standard', 'Express') group by shipping_type;

-- 7. Do subscribed customers spend more?
select subscription_status,  count(customer_id) as users ,
round(avg(purchase_amount),2) as avg_revenue, round(sum(purchase_amount),2) 
as total_revenue from customer_shopping_behavior group by subscription_status;

-- 8. Top 5 Products with highest discount usage
select item_purchased , count(item_purchased) as total_num_of_times_sold ,
count(case when discount_applied = "Yes" then 1 end) as num_of_times_sold_when_dis_applied,
count(case when discount_applied = "Yes" then 1 end) * 100.0 / count(*) as discount_percent
from customer_shopping_behavior group by item_purchased order by 
total_num_of_times_sold desc limit 5;

-- 9. Segment customer into new , returning, and loyal based on their total prev purchase
select case when previous_purchases = '0' then 'New Customer'
            when previous_purchases between 1 and 15 then 'Returning Customer'
            else 'Loyal Customer' end as customer_segment,
count(*) as customer_count from customer_shopping_behavior group by customer_segment; 

-- 10. What are the top 3 purchased product in each category?
with cte as (select category, item_purchased, count(item_purchased) as muost_purchased, 
rank() over(partition by category order by count(item_purchased) desc) as RNK 
from customer_shopping_behavior group by category, item_purchased ) 
select * from cte where rnk<3;


-- 11. Are customers who are repeat buyers (more than 5 prev purchase) also likely to subscribe?
select case when previous_purchases>5 then 'Repeat Buyers' else'Normal Buyers' end as 
customer_type, subscription_status, count(*) as customer_count, count(* ) * 100.0/ sum(count(*)) over 
(partition by case when previous_purchases > 5 then 'Repeat Buyers' else 'Normal Buyers' end ) as percents
 from customer_shopping_behavior group by customer_type, subscription_status;

-- 12. What is the revenue contribution of each age group?
-- Enables age based targeting, enhanced marketing efficiency.
select case when age between 18 and 25 then '18-25' 
            when age between 26 and 35 then '26-35'
            when age between 36 and 50 then '36-50'
            else '51+' end as age_group, 
round(sum(purchase_amount),2) as total_revenue from customer_shopping_behavior 
group by age_group order by total_revenue desc;




            



